### ISSUE TITLE
Option to ignore "pageNotFoundError" action from sending to Sentry

### ISSUE THREAD

**Issue by jhit** [1drop/shopware-sentry#13]
Shopware raises a exception for every 404 error. 
my Sentry Dashbord is filled with stupid web-spider requests that lead to 404 errors in shopware.
Could you please add a option to skip the pageNotFoundError action from sending to sentry?

**Comment by shyim** [comment]
I would prefer a list of exceptions in config.php which should be ignored like the Sentry Bundle. Or what you think guys? (And set 404 as Default)

**Comment by htuscher** [comment]
Sounds reasonable

**Comment by jhit** [comment]
Thanks @shyim
