### ISSUE TITLE
Error 500 after installation, Backend not useable

### ISSUE THREAD

**Issue by kaystrobach** [1drop/shopware-sentry#14]
System:
====

* Shopware 5.2.21
* Sentry Plugin 1.1.1 (installed via Shopware Store)
* PHP 7.0.11
* `uname -a`
Output: `FreeBSD qidone 10.2-RELEASE-p14 hostBSD 10.2-RELEASE-p14 #3: Sat Mar 19 18:10:30 CET 2016     root@fbsd10clone1.han-solo.net:/usr/obj/usr/src/sys/DMRKERNEL  amd64`

Plugin settings:
==== 
![image](https://user-images.githubusercontent.com/1185776/33338457-726f698a-d476-11e7-84ce-9134f9b2c30d.png)

Logfiles
====

apache error log
---

```
[Tue Nov 28 19:58:50.169539 2017] [fcgid:warn] [pid 41348] [client 93.228.xx.xxx:64334] mod_fcgid: stderr: PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException: The parameter "shopware.sentry" must be defined. in /shopware/var/cache/production_201703211201/proxies/ShopwareProductione928cc560381633e6f727b3a89e61338d3e91c3aProjectContainer.php:2160, referer: https://www.flooridoo.com/shop/backend/
```

Error during deaktivation from commandline:

![image](https://user-images.githubusercontent.com/1185776/33338716-3923b1a8-d477-11e7-96eb-27c79fdd6871.png)

stack trace
---

```
mod_fcgid: stderr: PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException: The parameter "shopware.sentry" must be defined. in /shopware/var/cache/production_201703211201/proxies/ShopwareProductione928cc560381633e6f727b3a89e61338d3e91c3aProjectContainer.php:2160, referer: https://www.domain.com/shop/backend/
mod_fcgid: stderr: Stack trace:, referer: https://www.domain.com/shop/backend/
mod_fcgid: stderr: #0 /shopware/custom/plugins/OdSentry/Components/SentryClient.php(31): ShopwareProductione928cc560381633e6f727b3a89e61338d3e91c3aProjectContainer->getParameter('shopware.sentry'), referer: https://www.domain.com/shop/backend/
mod_fcgid: stderr: #1 /shopware/custom/plugins/OdSentry/OdSentry.php(82): OdSentry\\Components\\SentryClient->setContainer(Object(ShopwareProductione928cc560381633e6f727b3a89e61338d3e91c3aProjectContainer)), referer: https://www.domain.com/shop/backend/
mod_fcgid: stderr: #2 /shopware/engine/Library/Enlight/Event/Handler/Default.php(91): OdSentry\\OdSentry->onStartDispatch(Object(Enlight_Con in /shopware/var/cache/production_201703211201/proxies/ShopwareProductione928cc560381633e6f727b3a89e61338d3e91c3aProjectContainer.php on line 2160, referer: https://www.domain.com/shop/backend/
```

**Comment by Quelk** [comment]
I think the entry for sentry in the config.php is required in the current version.

**Comment by shyim** [comment]
The CompilerPass sets a default configuration if it does not missing. I guess there is something wrong while building container....

Have you tried clearing complete cache folder in /var/cache?

**Comment by kaystrobach** [comment]
you are right, after adding the following lines to config.php the error 500 is gone.

![grafik](https://user-images.githubusercontent.com/1185776/33363369-607b5396-d4e0-11e7-9b6e-e057f80bc57e.png)

So it seems to me, that the defaults are faulty.

__PS: If you look into the description in the shopware store, there is no hint about that setting ...__

**Comment by htuscher** [comment]
shyim is right, the default configuration (if not explicitly set in config.php => which is NOT required) is added at a very early stage of the plugin bootstrapping which did not cause any problems until now.

**Comment by shyim** [comment]
Could you provide also a stack Trace?

**Comment by htuscher** [comment]
Hmm, I just tried it with a fresh installed demo shop:
![image](https://user-images.githubusercontent.com/5076356/33364343-56588196-d4e4-11e7-928a-8e79ce587d23.png)

And can't reproduce it.

**Comment by kaystrobach** [comment]
for sure, added it into the issue description

maybe the problem is, that i did installation in the following steps:

* download via shopware store (directly in shopware)
* install the plugin (automated step)
* configure the plugin (add dsn, etc.) 
* activate the plugin

after activation the installation stopped working

**Comment by htuscher** [comment]
Oh, I never got the installation of a plugin inside of Shopware working. Always get some weird response codes. E.g.:
![image](https://user-images.githubusercontent.com/5076356/33364852-8374e8ca-d4e6-11e7-8d1a-0ab5242d33e4.png)
I need to figure out a way to test this.

**Comment by kaystrobach** [comment]
Ahh your installation needs to be registered @shopware and reachable from the shopwarw servers ... strange stuff going on with it

**Comment by htuscher** [comment]
Actually it is registered

**Comment by htuscher** [comment]
I installed a new shop on which the registration worked and installed the plugin via the integrated shopware store. Can't reproduce the issue.

**Comment by kaystrobach** [comment]
Mhmm so let’s close it for now, I’m not so much into bsd maybe a platform specific problem 🤔

Atleast it works with the config.php settings, maybe it makes sense to point to the readme on github from the shopware store. 😉

Thanks a lot for your effort.
