### ISSUE TITLE
Lizenzierungsfehler

### ISSUE THREAD

**Issue by freedmo** [1drop/shopware-sentry#16]
Habe das Plugin über Shopware installiert, da ich annahm das dieser Fehler wegen der Github Version kommt, jedoch bleibt der Fehler das ich keine Lizenz besitze.

![image](https://user-images.githubusercontent.com/3056440/33548428-6e3198be-d8e7-11e7-8426-b97b347d27d2.png)

**Comment by shyim** [comment]
Kann man leider nix dagegen tun, außer die Meldung auszublenden => https://gist.github.com/shyim/6385391b72b72e98ce438c6af485bd53

**Comment by teiling88** [comment]
Das Plugin muss doch "nur" über einen Shopware Account erworben werden der mit dem Shop verknüpft ist oder nicht?

**Comment by freedmo** [comment]
> Habe das Plugin über Shopware installiert [...]

Hier auch noch der Screen habe es sogar hier installiert.

![image](https://user-images.githubusercontent.com/3056440/33559888-80d0018c-d90e-11e7-9a2b-34eff6086c6a.png)

Edit: Könnte an sich auch ein Fehler sein, da ich vorher per Git installiert hatte, ich werde es mal testen wenn Zeit dafür vorhanden, sowie auf einem leeren Exemplar testen.

**Comment by shyim** [comment]
Ansonsten an den Shopware Store Support wenden. Die können da denke ich mehr tun

**Comment by htuscher** [comment]
An den Shopware Support wenden: "Thomas Eiling - Enterprise Developer @shopware" :laughing:

**Comment by teiling88** [comment]
@hhoechtl - steht da was von Support?

**Comment by htuscher** [comment]
Vielleicht finde nur ich das witzig wenn es in einem Github issue um ein
Issue der Firma des Issuers geht und die Antwort ist sich an den Support
der eigenen Firma zu wenden

Thomas Eiling <notifications@github.com> schrieb am Di., 5. Dez. 2017,
08:33:

**Comment by teiling88** [comment]
Ich hab die Issue nicht angelegt geschweige die Empfehlung ausgesprochen unseren Support anzuschreiben?

**Comment by htuscher** [comment]
Oh sorry das hab ich nicht gesehen

Thomas Eiling <notifications@github.com> schrieb am Mi., 6. Dez. 2017,
09:19:
