### ISSUE TITLE
outdated SDK version

### ISSUE THREAD

**Issue by larsbo** [1drop/shopware-sentry#18]
Moin, Sentry grabs this note before every error:

![screenshot-2018-4-12 errorexception uncaught smartyexception unable to create directory var www clients client1 web7 web sh](https://user-images.githubusercontent.com/754074/38663882-63c0b3ae-3e38-11e8-8cb5-cada7652b6ba.png)

(translated to english using Google translate to satisfy @shyim 😄 )

**Comment by htuscher** [comment]
I have the same observation, but it's the latest PHP SDK 1.8.4 that is available on https://github.com/getsentry/sentry-php. Maybe they keep their PHP SDK not up to date.

**Comment by larsbo** [comment]
perhabs the message is outdated and it was saved togehter with the first occurence of an error? I found new errors without that info message 🙃

**Comment by htuscher** [comment]
No idea, but that might happen in the future and is not something we can automate. We can just release new versions of the plugin containing new SDK versions.
