### ISSUE TITLE
Update Sentry SDK

### ISSUE THREAD

**Issue by htuscher** [1drop/shopware-sentry#24]
Sentry SDK 2.x has been released. Therefore the plugin should be updated.

**Comment by larsbo** [comment]
is this still on your roadmap? 😃

**Comment by htuscher** [comment]
Yes it is, but we're currently very busy and I was on urgently needed vacation.

**Comment by htuscher** [comment]
@larsbo Can be tested. Will test it with our projects in the next 2 weeks or so and then release it.

**Comment by marcelloceschia** [comment]
@hhoechtl works for me and our clients

**Comment by htuscher** [comment]
We have issues in combination with Pickware plugins. Awaiting SDK update that could probably fix this.

**Comment by marcelloceschia** [comment]
@hhoechtl Ohh, we are also using some Pickware plugins, which one is it if you are mind to share.

**Comment by htuscher** [comment]
Every plugin as ViisonCommon is included in every plugin. The register a common error_handler which collides with the SentrySDK. See https://github.com/getsentry/sentry-php/issues/891 for more information
