### ISSUE TITLE
Allow overriding releases

### ISSUE THREAD

**Issue by ghobaty** [1drop/shopware-sentry#27]
Currently the release is parsed from Shopware version (i.e. `shopware.release.version`). It would be great if we could override this (e.g. via an environment or config variable).

**Comment by htuscher** [comment]
This tracks the version of the software used and is therefore correct.

I think you want to use the release tracking in Sentry => your project releases.
We do e.g. this in .gitlab-ci.yml:
```
    - NOW=$(date +"%Y%m%d%H%M%S")
    - >-
        curl -s "https://sentry/api/hooks/release/builtin/21/somekey/"
        -X POST
        -H "Content-Type: application/json"
        -d '{"version": "'${NOW}'"}'
```
So we can use the sentry features affected releases, resolved in next release etc.

**Comment by ghobaty** [comment]
Yes you are right. Thanks a lot!
