### ISSUE TITLE
502 Error instead of 404 redirect

### ISSUE THREAD

**Issue by wolv-dev** [1drop/shopware-sentry#3]
When error occurs in Shopware like "Uncaught Enlight_Controller_Exception: Controller "xxxxxxxxx" not found", than an 502 error is displayed instead of 404 redirect to error page or homepage

**Comment by shyim** [comment]
I cannot reproduce it ![Image](http://i.imgur.com/ZS7gfVB.png) with config.php

```php
<?php
return [
    'db' => [
        'username' => 'root',
        'password' => 'toor',
        'dbname' => 'sw52',
        'host' => 'mysql',
        'port' => '3306'
    ],
    'template' => [
        'forceCompile' => true,
    ],
    'csrfProtection' => [
        'frontend' => false,
        'backend' => false
    ],
];
```
