### ISSUE TITLE
Please update Sentry.io SDK to v2.4.3

### ISSUE THREAD

**Issue by jhit** [1drop/shopware-sentry#31]
Hello.
Could you possibly release a new version with a updated sentry sdk?

Thank you.

**Comment by htuscher** [comment]
The latest is 2.1.0: https://packagist.org/packages/sentry/sdk
We are on 2.0.4, so not really necessary.

**Comment by jhit** [comment]
Ok, but what tries sentr.io to tell me?
![image](https://user-images.githubusercontent.com/537665/92747503-8b81e580-f384-11ea-801e-ee18d02b1892.png)
The link goes to: 
https://packagist.org/packages/sentry/sentry#2.4.3
looks like there exist two different composer packages.

**Comment by htuscher** [comment]
Ah, the SDK is a package `sentry/sentry` which is a dependency of `sentry/sdk`. That's what I call misnamed.

**Comment by htuscher** [comment]
Version `2.0.3` has just been released to the store containing the newest sentry SDK version.

**Comment by larsbo** [comment]
The plugin.xml is invalid. The `version` entry must come before the `description` entry (tested with Shopware 5.6.8).

After the update from 1.x this error occures:

```
Uncaught TypeError: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /home/vagrant/www/shopware-5-6/custom/plugins/OdSentry/vendor/guzzlehttp/guzzle/src/Client.php on line 95 and defined in /home/vagrant/www/shopware-5-6/custom/plugins/OdSentry/vendor/guzzlehttp/guzzle/src/Client.php:179 

Stack trace: 
#0 /home/vagrant/www/shopware-5-6/custom/plugins/OdSentry/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\Client->request('setDefaultOptio...', 'verify', '/home/vagrant/w...') 
#1 /home/vagrant/www/shopware-5-6/engine/Shopware/Components/HttpClient/GuzzleFactory.php(41): GuzzleHttp\Client->__call('setDefaultOptio...', Array) 
#2 /home/vagrant/www/shopware-5-6/engine/Shopware/Components/HttpClient/GuzzleHttpClient.php(39): Shopware\Components\HttpClient\GuzzleFactory->createClient(Array) 
#3 /home/vagrant/www/shopware-5-6/var/cache/production_202008121209/proxies/ShopwareProduction00805b936edb74b5fe973faff7d069cf358c4f8aProjectContainer.php(6078): Shopware\C

File:/ home/ vagrant/ www/ shopware-5-6/ custom/ plugins/ OdSentry/ vendor/ guzzlehttp/ guzzle/ src/ Client.php
```

**Comment by shyim** [comment]
Could be maybe fixed with https://github.com/FriendsOfShopware/FroshPluginUploader/pull/75
