### ISSUE TITLE
Could not install package via composer

### ISSUE THREAD

**Issue by jochenmanz** [1drop/shopware-sentry#5]
Hi,

when trying to install the current plugin, i am recieving a error from composer:

composer require onedrop/shopware-sentry
->  Could not find package onedrop/shopware-sentry at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Best regards,
Jochen

**Comment by htuscher** [comment]
@shyim could you help? I'm on vacation

**Comment by vintagesucks** [comment]
There is no onedrop/shopware-sentry at packagist.org.

**Comment by shyim** [comment]
I don't have permission to create a package at onedrop organization

**Comment by htuscher** [comment]
The package is now available via composer. Sorry for the delay: https://packagist.org/packages/onedrop/shopware-sentry
