### ISSUE TITLE
Shopware Store

### ISSUE THREAD

**Issue by Linusten** [1drop/shopware-sentry#8]
Please add the Plugin to the Shopware community store,  actually i´m getting a license error when the plugin is installed

**Comment by shyim** [comment]
The plugin is currently in review. @hhoechtl could you check the state?

**Comment by htuscher** [comment]
Shopware rejects that plugin from the store because the Sentry library contains `$_POST` in the code.
```
The following files contain POST globals: /OdSentry/vendor/sentry/sentry/lib/Raven/Client.php
``` 
is the response from the auto-check in the Shopware store. I already spoke with @ndzoesch regarding this issue but I didn't get a response yet.

**Comment by shyim** [comment]
He is tomorrow back from vacation :)

**Comment by htuscher** [comment]
@ndzoesch could you please comment or hint how we could solve this 3rd party library failing automatic code checking issues?

**Comment by shyim** [comment]
@hhoechtl is here a new news about the plugin in store?

**Comment by htuscher** [comment]
Theoretically it's in the store. I receive buy notifications but I can't find it and the account says it's not available in store. They're really making this complicated if you have a third party library inside :-(

**Comment by shyim** [comment]
Could you try to get this fixed with the Shopware Sales Support?

**Comment by htuscher** [comment]
I sent them a mail as I'm very busy atm.

**Comment by htuscher** [comment]
Miracles happen: http://store.shopware.com/detail/index/sArticle/164364/number/ods3018122618489
